from . import bsi_salon_service
from . import bsi_salon_package
from . import bsi_salon_membership
from . import bsi_salon_membership_subscription
from . import bsi_salon_location
from . import bsi_salon_team_member
from . import bsi_salon_testimonial
from . import bsi_salon_award
from . import bsi_salon_value
from . import bsi_salon_about_content
from . import bsi_salon_chair
from . import bsi_salon_time_slot
from . import bsi_salon_loyalty_point
from . import bsi_salon_referral_wizard
from . import bsi_salon_reschedule_wizard
from . import res_partner
from . import res_config_settings
from . import bsi_salon_booking_mixin
from . import bsi_salon_booking_request
from . import bsi_salon_booking_service_line
from . import crm_lead
from . import sale_order
from . import account_move
from . import rating_rating
